#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" | tee /etc/default/haproxy

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 18.212.192.18:80 check
    server web-02 52.90.174.46:80 check
EOF

# Restart HAProxy
service haproxy restart


